name: FuelFly
version: '1.0.0'
main: org.htilssu.fuelfly.FuelFly
api-version: '1.16'

permissions:
  fuel.fly:
    description: allow player use fuel to fly
    default: op
  fuel.give:
    description: give fuel to a player
    default: op
    children:
      fuel.give.player: true